In [1]:
import numpy as np

In [2]:
a = np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(a, axis = 0)

In [5]:
mean_a

array([2. , 8.4])

In [6]:
a_centered = np.array([[a[:,0]-np.full((5,),mean_a[0])], [a[:,1]-np.full((5,),mean_a[1])]])

In [7]:
a_centered

array([[[-1. ,  0. ,  1. ,  1. , -1. ]],

       [[-2.4, -0.4,  2.6,  1.6, -1.4]]])

In [8]:
a_centered_sp = np.inner(a_centered[0,:], a_centered[1,:])

In [9]:
a_centered_sp

array([[8.]])

In [10]:
a_centered_sp / (a.shape[0]-1)

array([[2.]])

In [11]:
np.cov(a.transpose())[0,1]

2.0